version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - FIREBASE_CONFIG=${FIREBASE_CONFIG}
      - ENABLE_BACKGROUND_SCRAPING=true
    volumes:
      - ./app:/app/app
      - ./static:/app/static
      - ./firebase-credentials.json:/app/firebase-credentials.json
    restart: unless-stopped